### ISSUE TITLE
PSPNet question

### ISSUE THREAD

**Issue by sydney0zq** [speedinghzl/pytorch-segmentation-toolbox#10]
In `networks/pspnet.py`, we could notice function `PSPModule/_make_stage`, it doesn't include `ReLU` nonlinear operation. (Also the activation of `InPlaceABNSync` is `none`). But I refer to the origin repo, it can be visualized as follows: 
![img](https://i.loli.net/2018/12/11/5c0f8617767f8.png)

Therefore the removal of this `ReLU` is on purpose or not?

**Comment by speedinghzl** [comment]
InPlaceABNSync contains PReLU by default. This replacement (ReLU->PReLU) is for memory saving. Please refer to [this paper](https://arxiv.org/abs/1712.02616) for more details.
