### ISSUE TITLE
Reimplement results

### ISSUE THREAD

**Issue by LeiyuanMa** [speedinghzl/pytorch-segmentation-toolbox#11]
Due to GPU limitation,I set the BS=2,STEPS= 160000 and GPU_IDS= 0,(also Titan XP),But I'm confused that the my reimplement results is not so well,mIOU is only 0.687...could you double check are there some details go wrong?As I found the args.ohem was set to false,the set_bn_eval and set_bn_momentum function seems not working...As for evaluate,It seems that args.recurrence working in any way...etc..I'm not sure if these will influence the reimplement results or not,could you give me some advice?

**Comment by speedinghzl** [comment]
Please refer to [ReadMe](https://github.com/speedinghzl/pytorch-segmentation-toolbox#requirements)! This repo requires 4 x 12g GPUs because the large batch size is important for high performance.

**Comment by LeiyuanMa** [comment]
Thanks,I tried with 2 gpu,the performance reach 0.756..

**Comment by speedinghzl** [comment]
Ok. It's a reasonable result. If you could achieve higher performance if using 4 GPUs.
