### ISSUE TITLE
the adjust_learning_rate

### ISSUE THREAD

**Issue by 1453042287** [speedinghzl/pytorch-segmentation-toolbox#12]
why U only set optimizer.param_groups[0] = lr ?

**Comment by 1453042287** [comment]
i saw other's implementation like this:

for group in optimizer.param_groups:
      group['lr'] = now_lr

what's the difference?

**Comment by speedinghzl** [comment]
@1453042287 In my code, optimizer.param_groups[0]['lr'] = lr rather than optimizer.param_groups[0] = lr.
