### ISSUE TITLE
error in 8 GPU server

### ISSUE THREAD

**Issue by Millczc** [speedinghzl/pytorch-segmentation-toolbox#17]
Hi,
   I had run the project in my server. My server has 2 CPU and 8 GPU(GTX 1080TI). But when i run the project by used 8 GPU, speed is so slowly(20+s/iter), and iter be 7 or 8,the program stop. when I use 4 GPU, the speed is so quickly(2s/iter). Did you have same problem?

**Comment by speedinghzl** [comment]
@Millczc Yes, I have the same problem. Please refer to an Inplace-ABN [issue](https://github.com/mapillary/inplace_abn/issues/44).
