### ISSUE TITLE
about the implementation of DataParallelModel and DataParallelCriterion in ./utils/encoding.py

### ISSUE THREAD

**Issue by yongjingli** [speedinghzl/pytorch-segmentation-toolbox#19]
Hi, speedinghzl. It seems that the implementation of DataParallelModel and DataParallelCriterion in ./utils/encoding.py  are not integral.

**Comment by speedinghzl** [comment]
@yongjingli Yes, they are not integral. You can replace them with default DataParallel in Pytorch. In fact, I use them for balancing the memory usage on every GPUs.
