### ISSUE TITLE
Program received signal SIGSEGV, Segmentation fault.

### ISSUE THREAD

**Issue by Silliam** [speedinghzl/pytorch-segmentation-toolbox#2]
I tried the code, but the program stopped when the tensor x get into dsn. I locate the Error with GDB and found ：

**Program received signal SIGSEGV, Segmentation fault.
0x00002aaafb067270 in unsigned long thrust::system::cuda::detail::bulk_::detail::block_size_with_maximum_potential_occupancy<thrust::system::cuda::detail::bulk_::detail::cuda_launch_config_detail::util::zero_function<unsigned long> >(thrust::system::cuda::detail::bulk_::detail::function_attributes_t const&, thrust::system::cuda::detail::bulk_::detail::device_properties_t const&, thrust::system::cuda::detail::bulk_::detail::cuda_launch_config_detail::util::zero_function<unsigned long>) [clone .isra.24] ()
   from /home/my/code/pytorch-segmentation-toolbox-master/libs/_ext/__ext.so**

I don't understand the error in .so file, how can I fix this problem?  thanks !

**Comment by speedinghzl** [comment]
@Silliam This repo requires 4x 12G GPUs. Before running this code, please make sure InPlace-ABN have been compiled.

**Comment by Silliam** [comment]
> @Silliam This repo requires 4x 12G GPUs. Before running this code, please make sure InPlace-ABN has been compiled.

Must it need 4x 12G GPUs?  I build abn in a mechine with 8 GPUS, but noly run the code with two. Does this matter?

**Comment by speedinghzl** [comment]
4x 12G GPUS are used for reproducing the results. Of course, you can run this code with small batch size (i.e. 4) under two gpus.
