### ISSUE TITLE
The activation "ReLU" in models?

### ISSUE THREAD

**Issue by CS-Jackson** [speedinghzl/pytorch-segmentation-toolbox#20]
Hi, @speedinghzl . Thanks for the great job. I have a little problem about the activation using in the model. As in the inplaceABN paper, the ReLU activation is not invertible. Do you use the ReLU activation to train the model?

**Comment by speedinghzl** [comment]
Yes, I use the ReLU activation without in-place operation.

**Comment by CS-Jackson** [comment]
> Yes, I use the ReLU activation without in-place operation.

Thank you for the answer. By the way, can you share the weight training on CityScapes?

**Comment by speedinghzl** [comment]
I will release the trained model later. Now I am focusing on the conference submission. If you want to obtain the high-performance segmentation result of Cityscapes, I refer you to my another repo [CCNet](https://github.com/speedinghzl/CCNet#models).

**Comment by erichhhhho** [comment]
@speedinghzl Any update for the pretrained PSPNet?
