### ISSUE TITLE
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead

### ISSUE THREAD

**Issue by jizongFox** [speedinghzl/pytorch-segmentation-toolbox#29]
I don't know if anyone has encountered the same thing as me.
After builidng the libs, I have this issue when running train.py
Thanks for your help.

**Comment by lzrobots** [comment]
cuda problem. make sure you set your cuda path correct.

**Comment by lzrobots** [comment]
are you using pytorch1.0? this repo only support pytorch 0.4

**Comment by jizongFox** [comment]
@lzrobots  Hi, thanks for the reply, I am using PyTorch 1.0 and does there exists any way to adapte the code to PyTorch 1.0?

**Comment by lzrobots** [comment]
https://github.com/mapillary/inplace_abn/issues/84
