### ISSUE TITLE
Problem training in BS=4 in 4 GPU (1080TI).

### ISSUE THREAD

**Issue by Endless-Hao** [speedinghzl/pytorch-segmentation-toolbox#33]
Hello, I use 4 GPU (1080TI). So I change the batch_size to 4. When I was training in iter=895, I got an error. How I can solve it? Error blew:
![image](https://user-images.githubusercontent.com/19277849/53611040-0e5ea780-3c08-11e9-8f56-709c93ea9458.png)

**Comment by speedinghzl** [comment]
The error is always caused by the broken file or nonexistent file. Maybe you need to check your cityscape dataset.

**Comment by Endless-Hao** [comment]
Thank you
