### ISSUE TITLE
Problem python bulid.py in pytorch1.0.

### ISSUE THREAD

**Issue by longredzhong** [speedinghzl/pytorch-segmentation-toolbox#34]
'''Traceback (most recent call last):
  File "build.py", line 3, in <module>
    from torch.utils.ffi import create_extension
  File "/home/longred/anaconda3/envs/CSTC/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
'''

**Comment by sbelharbi** [comment]
Hello,
        Any update on this issue?

**Comment by speedinghzl** [comment]
This repo doesn't support Pytorch 1.0.
