### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by linqinghong** [speedinghzl/pytorch-segmentation-toolbox#35]
Hi, I find some problem exist in bn from 0.4 to 1.0,so i can reach the mIoU like 0.4 and i can't find the problem in where. 
can you implement a pytorch1.0 version? it will be very helpful~
thank~

**Comment by speedinghzl** [comment]
Reduplicate [issue](https://github.com/speedinghzl/pytorch-segmentation-toolbox/issues/36).
